version: 2
jobs:
  build:
    docker:
      - image: poldrack/statsthinking21
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b1:a0:7e:1a:a0:59:95:4f:a3:1a:0d:fb:1f:a3:69:96"
      - checkout
      - run:
           name: rendering pdf
           command: |
             make render-pdf
           no_output_timeout: 1200
      - run:
           name: rendering epub
           command: |
             make render-epub
           no_output_timeout: 1200
      - run:
           name: rendering gitbook
           command: |
             make render-gitbook
           no_output_timeout: 1200
      - run:
           name: check out site repo
           command: |
             cd /tmp
             ssh-keyscan github.com >> ~/.ssh/known_hosts
             git clone git@github.com:statsthinking21/statsthinking21-core-site.git
             cd statsthinking21-core-site
             cp -r ~/project/_book/* . 
             git add .
             git config --global user.email poldrack@gmail.com
             git config --global user.name "Russ Poldrack"
             git commit -m"automated update"
             git push origin master

